### ISSUE TITLE
Show FPS graphical glitch

### ISSUE THREAD

**Issue by ivanmestre** [devmiyax/yabause#621]
On the Android 2.6.4 build there is a weird graphical glitch when using the Keep Aspect Ratio option and Show FPS option. It seems like the screen is duplicated, and one copy is layered on top of the other. If the FPS counter is disabled the glitch goes away.

![Screenshot_20190808-193335](https://user-images.githubusercontent.com/6786286/62742274-4dddbb00-ba14-11e9-8d7a-a391b15f083c.png)
![Screenshot_20190808-193347](https://user-images.githubusercontent.com/6786286/62742275-4e765180-ba14-11e9-90e5-c06002806794.png)

**Comment by ivanmestre** [comment]
Glitch still exists after the Android 2.6.6 update

**Comment by devmiyax** [comment]
fixed in 2.6.8.

**Comment by ivanmestre** [comment]
There are still graphical glitches on 2.6.8 when having the FPS counter enabled:

Fighters Megamix (check the right side of the image):
![Screenshot_20190812-163618](https://user-images.githubusercontent.com/6786286/62992377-8ffa6880-be29-11e9-8695-7d950a7de02a.png)

How it looks without the FPS counter:
![Screenshot_20190812-163701](https://user-images.githubusercontent.com/6786286/62992419-b0c2be00-be29-11e9-8da2-72aad6510b7c.png)

Panzer Dragoon (lower left side of the image):
![Screenshot_20190814-002131](https://user-images.githubusercontent.com/6786286/62992433-bae4bc80-be29-11e9-8006-442cac20d781.png)

**Comment by devmiyax** [comment]
Can you share your Graphics settings?

**Comment by ivanmestre** [comment]
FPS = On
Keep original aspect rate = On
Lock Landscape Mode = On
Polygon generation type = Triangle using perspective correction
Rendering resolution = 2x
RGB resolution = Original
Use compute shader = On

I've also tried with Rendering Resolution = Original, Disabling Compute Shader and trying the other Polygon Generation Type, but the glitches still happen with FPS = On.
My device is a Xiaomi Mi A2, it has a Snapdragon 660 and it's running Android 9.

**Comment by ivanmestre** [comment]
Fixed on latest, 2.7.2
